#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Feb 21 00:01:13 +07 2024
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto abdb8688a0284bf3923b875a0bb7e5ab --incr --debug typical --relax --mt 8 -d "TARGET_FPGA=" -d "TARGET_SIMULATION=" -d "TARGET_TEST=" -d "TARGET_VIVADO=" -d "TARGET_XILINX=" -generic_top "NumPorts=32'd1" -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_tc_sram_behav xil_defaultlib.tb_tc_sram xil_defaultlib.glbl -log elaborate.log"
xelab -wto abdb8688a0284bf3923b875a0bb7e5ab --incr --debug typical --relax --mt 8 -d "TARGET_FPGA=" -d "TARGET_SIMULATION=" -d "TARGET_TEST=" -d "TARGET_VIVADO=" -d "TARGET_XILINX=" -generic_top "NumPorts=32'd1" -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_tc_sram_behav xil_defaultlib.tb_tc_sram xil_defaultlib.glbl -log elaborate.log

